---
title: "Reproducibility with {gtsummary}"
author: "Daniel D. Sjoberg, Karissa Whiting"
date: "August 28, 2020"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, my-theme.css]
    nature:
      ratio: 16:9
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
set.seed(78987)
library(xaringanthemer)
library(tidyverse)
library(gtsummary) 

style_mono_accent(
  base_color = mskRvis::msk_palettes$contrast[1],
  # primary_color = mskRvis::msk_palettes$contrast[1], 
  # secondary_color = mskRvis::msk_palettes$contrast[2],
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
# xaringanExtra::use_webcam()
```


```{r xaringan-logo, echo=FALSE}
# xaringanExtra::use_logo(
#   "figures/msk-black-logo.png",
#   width = "270px",
#   position = xaringanExtra::css_position(top = 0, right = 0),
#   exclude_class = c("inverse", "hide_logo")
# )
```

```{r setup, include=FALSE}
# xaringan::inf_mr()
options(htmltools.dir.version = FALSE)

# helper function to save gtsummary objects
my_gtsave <- function(x) {
  # if being knitted, then skip (save your objects before you knit)
  if (isTRUE(getOption('knitr.in.progress'))) return(invisible(NULL))
  
  path <- file.path("images", paste0(x, ".png"))
  x <- eval(parse(text=x))
  if (inherits(x, "gtsummary")) x <- as_gt(x)
  gt::gtsave(x, path)
}
my_gtsave("tbl_summary_1")
```

```{r child='01-background.Rmd'}
```

---
```{r child='02-tbl_summary.Rmd'}
```

---
```{r child='03-tbl_regression.Rmd'}
```

---
```{r child='04-themes.Rmd'}
```

---
```{r child='05-print_engines.Rmd'}
```

---
```{r child='06-thank_you.Rmd'}
```